### PR TITLE
Show summary by default in myshowq

### PR DESCRIPTION
**Pull request by wpoely86**
@itkovian please review

### CODE REVIEW

**Comment by stdweird** [comment]
test this please

**Comment by stdweird** [comment]
@wpoely86 don't worry about the failing tests, not related to this PR

**Comment by itkovian** [comment]
@wpoely86 Please add yourself as an author in the script's docstring.

**Comment by wpoely86** [comment]
@itkovian done

**Comment by JensTimmerman** [comment]
jenkins: test this please

**Comment by stdweird** [comment]
@wpoely86 can you rebase on master (should fix your tests)

**Comment by wpoely86** [comment]
jenkins: test this please

**Comment by wpoely86** [comment]
jenkins: test this please

**Pull request merged**
