### PR TITLE
phanpy has no swap anymore, + emperical data shows that jobs over 384…

### PR DESCRIPTION
**Pull request by JensTimmerman**
… don't start

### CODE REVIEW

**Comment by boegel** [comment]
Good to go (if the tests pass, that is).

**Comment by boegel** [comment]
@JensTimmerman: do we really want to pollute this PR with updating to `2016` in the copyright lines? should be done in a separate trivial-to-merge PR?

**Comment by JensTimmerman** [comment]
well, you wanted the tests to pass..
and this is still pretty trivial, but yes, sure

**Comment by boegel** [comment]
Changing the copyright line fixes the tests?

**Comment by JensTimmerman** [comment]
yes, the test fail if the copyright header is wrong. this is a feature from vsc.install
see https://github.com/hpcugent/vsc-jobs/pull/58

**Comment by stdweird** [comment]
@JensTimmerman why was this merged? phanpy nodes not having swap enabeld is a bug, not some feature to dance around in the submifilter

**Comment by boegel** [comment]
@stdweird: well, I merged it, not @JensTimmerman

Having this merged in the submitfilter is not terrible, but yes, it's wrong.

Not having swap at all is a bigger issue, now that you pointed it out...

**Comment by JensTimmerman** [comment]
people were confused about jobs never starting on phanpy (admins as well as users, see also hpc-admin), at least now they will get the correct warning message when submitting jobs that request to much vmem.

**Comment by stdweird** [comment]
@JensTimmerman yes, but when phanpy has no swap, that's not good. it looks like some el7.1 issue/feature that popped up after the phanpy nodes were reinstalled. (also, without swap, no overcommit)

**Pull request merged**
